services:
  app:
    image: ghcr.io/longluu33931/phan-bon-max:latest
    container_name: PHAN_BON_MAX
    restart: always
    env_file:
      - .env
    ports:
      - "5762:5762"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.json:/config.json
    environment:
      - DOCKER_CONFIG=/
    command: --interval 20 --cleanup --remove-volumes
    restart: always
